// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ASPNETcore5Homework.Models
{
    public partial class Department_DeleteResult
    {
    }
}
